{{- include "pinglib.service-cluster" (list . "pingdirectory") -}}


{{- define "pingdirectory.service-cluster" -}}
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
{{- end -}}